# 0. Setup Paths

In [2]:
WORKSPACE_PATH = 'Tensorflow/workspace'
SCRIPTS_PATH = 'Tensorflow/scripts'
APIMODEL_PATH = 'Tensorflow/models'
ANNOTATION_PATH = f'{WORKSPACE_PATH}/annotations'
IMAGE_PATH = f'{WORKSPACE_PATH}/images'
MODEL_PATH = f'{WORKSPACE_PATH}/models'
PRETRAINED_MODEL_PATH = f'{WORKSPACE_PATH}/pre_trained_models'
CONFIG_PATH = f'{MODEL_PATH}/my_ssd_mobnet/pipeline.config'
SSD_MOBNET = f'{MODEL_PATH}/my_ssd_mobnet'

# 1. Create Labels Map

In [3]:
labels = [
    {'name': 'Hello', 'id': 1},
    {'name': 'Thank You', 'id': 2},
    {'name': 'I Love You', 'id': 3},
    {'name': 'Yes', 'id': 4},
    {'name': 'No', 'id': 5}
]

In [5]:
with open(ANNOTATION_PATH + '/label_map.pbtxt', 'w') as f:
    for label in labels:
        f.write('item { \n')
        f.write('\tname:\'{}\'\n'.format(label['name']))
        f.write('\tid:{}\n'.format(label['id']))
        f.write('}\n')

# 2. Clone Tensoflow pretrained models from Tensorflow Models Zoo

In [4]:
# !cd Tensorflow && git clone https://github.com/tensorflow/models

# 3. Create TF Records

In [4]:
import os

In [16]:
!python {SCRIPTS_PATH + '/generate_tfrecord.py'} -x {IMAGE_PATH + '/train'} -l {ANNOTATION_PATH + '/label_map.pbtxt'} -o {ANNOTATION_PATH + '/train.record'}
!python {SCRIPTS_PATH + '/generate_tfrecord.py'} -x {IMAGE_PATH + '/test'} -l {ANNOTATION_PATH + '/label_map.pbtxt'} -o {ANNOTATION_PATH + '/test.record'}

Successfully created the TFRecord file: Tensorflow/workspace/annotations/train.record
Successfully created the TFRecord file: Tensorflow/workspace/annotations/test.record


# 4. Copy Model Config to Training folder

In [5]:
CUSTOM_MODEL_NAME = 'my_ssd_mobnet'

In [4]:
!mkdir {MODEL_PATH+'/'+CUSTOM_MODEL_NAME}

mkdir: {MODEL_PATH+: No such file or directory


In [5]:
!cp {PRETRAINED_MODEL_PATH+'/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/pipeline.config'} {MODEL_PATH+'/'+CUSTOM_MODEL_NAME}

cp: {PRETRAINED_MODEL_PATH+/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/pipeline.config}: No such file or directory


# 5. Update Config for Transfer Learning

In [6]:
import tensorflow as tf
from object_detection.utils import config_util
from object_detection.protos import pipeline_pb2
from google.protobuf import text_format

2023-09-14 10:52:04.450925: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [7]:
config = config_util.get_configs_from_pipeline_file(CONFIG_PATH)

In [10]:
config

{'model': ssd {
   num_classes: 5
   image_resizer {
     fixed_shape_resizer {
       height: 320
       width: 320
     }
   }
   feature_extractor {
     type: "ssd_mobilenet_v2_fpn_keras"
     depth_multiplier: 1.0
     min_depth: 16
     conv_hyperparams {
       regularizer {
         l2_regularizer {
           weight: 3.9999998989515007e-05
         }
       }
       initializer {
         random_normal_initializer {
           mean: 0.0
           stddev: 0.009999999776482582
         }
       }
       activation: RELU_6
       batch_norm {
         decay: 0.996999979019165
         scale: true
         epsilon: 0.0010000000474974513
       }
     }
     use_depthwise: true
     override_base_feature_extractor_hyperparams: true
     fpn {
       min_level: 3
       max_level: 7
       additional_layer_depth: 128
     }
   }
   box_coder {
     faster_rcnn_box_coder {
       y_scale: 10.0
       x_scale: 10.0
       height_scale: 5.0
       width_scale: 5.0
     }
   }
   match

In [19]:
pipeline_config = pipeline_pb2.TrainEvalPipelineConfig()
with tf.io.gfile.GFile(CONFIG_PATH, 'r') as f:
    proto_str = f.read()
    text_format.Merge(proto_str, pipeline_config)

In [20]:
pipeline_config.model.ssd.num_classes = 5
pipeline_config.train_config.batch_size = 4
pipeline_config.train_config.fine_tune_checkpoint = PRETRAINED_MODEL_PATH+'/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/checkpoint/ckpt-0'
pipeline_config.train_config.fine_tune_checkpoint_type = "detection"
pipeline_config.train_input_reader.label_map_path= ANNOTATION_PATH + '/label_map.pbtxt'
pipeline_config.train_input_reader.tf_record_input_reader.input_path[:] = [ANNOTATION_PATH + '/train.record']
pipeline_config.eval_input_reader[0].label_map_path = ANNOTATION_PATH + '/label_map.pbtxt'
pipeline_config.eval_input_reader[0].tf_record_input_reader.input_path[:] = [ANNOTATION_PATH + '/test.record']

In [21]:
config_text = text_format.MessageToString(pipeline_config)
with tf.io.gfile.GFile(CONFIG_PATH, 'wb') as f:
    f.write(config_text)

# 6. Train the model

In [17]:
print("""python {}/research/object_detection/model_main_tf2.py --model_dir={}/{} --pipeline_config_path={}/{}/pipeline.config --num_train_steps=5000""".format(APIMODEL_PATH, MODEL_PATH,CUSTOM_MODEL_NAME,MODEL_PATH,CUSTOM_MODEL_NAME))


python Tensorflow/models/research/object_detection/model_main_tf2.py --model_dir=Tensorflow/workspace/models/my_ssd_mobnet --pipeline_config_path=Tensorflow/workspace/models/my_ssd_mobnet/pipeline.config --num_train_steps=5000


# 7. Load Train Model from checkpoint

In [8]:
import os
from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as viz_utils
from object_detection.builders import model_builder

In [9]:
# Load pipeline config and build a detection model
configs = config_util.get_configs_from_pipeline_file(CONFIG_PATH)
detection_model = model_builder.build(model_config=configs['model'], is_training=False)

# Restore checkpoint
ckpt = tf.compat.v2.train.Checkpoint(model=detection_model)
ckpt.restore(os.path.join(SSD_MOBNET, 'ckpt-11')).expect_partial()

@tf.function
def detect_fn(image):
    image, shapes = detection_model.preprocess(image)
    prediction_dict = detection_model.predict(image, shapes)
    detections = detection_model.postprocess(prediction_dict, shapes)
    return detections

# 8. Detect in Real Time

In [10]:
import cv2 
import numpy as np

In [11]:
category_index = label_map_util.create_category_index_from_labelmap(ANNOTATION_PATH+'/label_map.pbtxt')

In [19]:
cap = cv2.VideoCapture(0)
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

In [20]:
while True:
    ret, frame = cap.read()
    image_np = np.array(frame)


    input_tensor = tf.convert_to_tensor(np.expand_dims(image_np, 0), dtype=tf.float32)
    detections = detect_fn(input_tensor)
    
    num_detections = int(detections.pop('num_detections'))
    detections = {key: value[0, :num_detections].numpy() for key, value in detections.items()}

    detections['num_detections'] = num_detections
    
    # detections classes as INT
    detections['detection_classes'] = detections['detection_classes'].astype(np.int64)

    label_id_offset = 1
    image_np_with_detections = image_np.copy()

    viz_utils.visualize_boxes_and_labels_on_image_array(
                image_np_with_detections,
                detections['detection_boxes'],
                detections['detection_classes']+label_id_offset,
                detections['detection_scores'],
                category_index,
                use_normalized_coordinates=True,
                max_boxes_to_draw=1,
                min_score_thresh=.05,
                agnostic_mode=False)

    print('ACA', detections['detection_boxes'])

    cv2.imshow('object detection',  image_np_with_detections)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        cap.release()
        break

cv2.destroyAllWindows()
cap.release()

ACA [[0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         0.99728763]
 [0.         0.1373657  1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.9232029  0.8738796  1.         0.98944634]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.07332855 0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         0.99728763]
 [0.         0.         0.8937917  1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         0.8576395 ]
 [0.9222777  0.8224472  0.9980687  0.95048535]
 [0.92220

2023-09-14 12:00:07.010 python[78436:1163872] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (248.84 secs).


ACA [[0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         0.99728763]
 [0.         0.1373657  1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.9232029  0.8738796  1.         0.98944634]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.07332855 0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         0.99728763]
 [0.         0.         0.8937917  1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         1.        ]
 [0.         0.         1.         0.8576395 ]
 [0.9222777  0.8224472  0.9980687  0.95048535]
 [0.92220

# 9. Save Graph

In [37]:
!mkdir {SSD_MOBNET+'/export'} && mkdir {SSD_MOBNET+'/converted'}

In [22]:
print(f"python {APIMODEL_PATH}/research/object_detection/exporter_main_v2.py --input_type=image_tensor --pipeline_config_path={CONFIG_PATH} --trained_checkpoint_dir={SSD_MOBNET} --output_directory={SSD_MOBNET}/export")

python Tensorflow/models/research/object_detection/exporter_main_v2.py --input_type=image_tensor --pipeline_config_path=Tensorflow/workspace/models/my_ssd_mobnet/pipeline.config --trained_checkpoint_dir=Tensorflow/workspace/models/my_ssd_mobnet --output_directory=Tensorflow/workspace/models/my_ssd_mobnet/export


: 

# 10. Convert to TFJS model

In [51]:
!pip install PyYAML==5.3.1

  Using cached PyYAML-5.3.1-cp39-cp39-macosx_10_9_x86_64.whl
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 6.0.1
    Uninstalling PyYAML-6.0.1:
      Successfully uninstalled PyYAML-6.0.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flax 0.6.2 requires PyYAML>=5.4.1, but you have pyyaml 5.3.1 which is incompatible.

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip


In [52]:
!pip install tensorflowjs

  Using cached PyYAML-6.0.1-cp39-cp39-macosx_10_9_x86_64.whl (197 kB)
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 5.3.1
    Uninstalling PyYAML-5.3.1:
      Successfully uninstalled PyYAML-5.3.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tf-models-official 2.13.1 requires pyyaml<5.4.0,>=5.1, but you have pyyaml 6.0.1 which is incompatible.

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip


In [54]:
print(f"tensorflowjs_converter --input_format=tf_saved_model --output_node_names='detection_boxes,detection_classes,detection_features,detection_multiclass_scores,detection_scores,num_detections,raw_detection_boxes,raw_detection_scores' --output_format=tfjs_graph_model --signature_name=serving_default {SSD_MOBNET}/export/saved_model {SSD_MOBNET}/converted")

tensorflowjs_converter --input_format=tf_saved_model --output_node_names='detection_boxes,detection_classes,detection_features,detection_multiclass_scores,detection_scores,num_detections,raw_detection_boxes,raw_detection_scores' --output_format=tfjs_graph_model --signature_name=serving_default Tensorflow/workspace/models/my_ssd_mobnet/export/saved_model Tensorflow/workspace/models/my_ssd_mobnet/converted


Tried only exporting needed nodes

In [21]:
print(f"tensorflowjs_converter --input_format=tf_saved_model --output_node_names='detection_boxes,detection_classes,detection_scores' --output_format=tfjs_graph_model --signature_name=serving_default {SSD_MOBNET}/export/saved_model {SSD_MOBNET}/converted")

tensorflowjs_converter --input_format=tf_saved_model --output_node_names='detection_boxes,detection_classes,detection_scores' --output_format=tfjs_graph_model --signature_name=serving_default Tensorflow/workspace/models/my_ssd_mobnet/export/saved_model Tensorflow/workspace/models/my_ssd_mobnet/converted
